## 1. Import Libraries

# Titanic Survival Prediction using Iguanas

This notebook demonstrates a complete end-to-end example of using **Iguanas** for rule-based classification on the Kaggle Titanic dataset. 

The workflow includes:
1. Generating candidate rules using XGBoost
2. Filtering and selecting high-quality rules
3. Combining rules using different strategies
4. Generating predictions for submission

In [1]:
import numpy as np
import polars as pl
from xgboost import XGBClassifier

from iguanas.metrics import compute_metrics
from iguanas.rule_analysis import generate_rule_performance_report
from iguanas.rule_combination import (
    combine_rules_beam_search,
    combine_rules_cumulative,
    combine_rules_greedy,
)
from iguanas.rule_evaluation import apply_rules
from iguanas.rule_generation import rule_grid_search_parallel_scales
from iguanas.rule_selection import filter_correlated_rules

## 2. Load and Prepare Data

Load the Titanic training data and separate features from the target variable (Survived).

In [2]:
train = pl.read_csv("../../../kaggle/titanic/train.csv").drop("PassengerId")
X_train = train.drop("Survived")
y_train = train["Survived"]

Extract numeric columns for rule generation:

In [3]:
num_columns = [col for col, dtype in X_train.schema.items() if dtype in [pl.Int64, pl.Float64]]
num_columns

['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

## 3. Generate Candidate Rules

Use XGBoost-based grid search to generate candidate rules. The `rule_grid_search` function trains models with different `scale_pos_weight` values and extracts rules from the decision trees.

In [4]:
estimator = XGBClassifier(n_estimators=10, max_depth=4, eval_metric="logloss", random_state=0)
rules = rule_grid_search_parallel_scales(
    estimator,
    X_train[num_columns].to_pandas(),
    y_train.to_pandas(),
    scale_pos_weight_vec=np.logspace(-3, 3, 50),
)
rules = rules.unique("rule")

In [5]:
rules.head(3)

shape: (3, 4)
┌─────────────────────────────────┬──────┬────────────────┬──────────────────┐
│ rule                            ┆ tree ┆ transformation ┆ scale_pos_weight │
│ ---                             ┆ ---  ┆ ---            ┆ ---              │
│ str                             ┆ i64  ┆ str            ┆ f64              │
╞═════════════════════════════════╪══════╪════════════════╪══════════════════╡
│ (X["Fare"] >= 75.25)            ┆ 4    ┆ Baseline       ┆ 0.009541         │
│ (X["Fare"] >= 7.7333) & (X["Fa… ┆ 8    ┆ Baseline       ┆ 14.563485        │
│ (X["Fare"] >= 10.5) & (X["Age"… ┆ 6    ┆ Baseline       ┆ 0.281177         │
└─────────────────────────────────┴──────┴────────────────┴──────────────────┘

## 4. Filter High-Quality Rules

Apply the generated rules to the training data, compute performance metrics, and filter based on:
- Minimum precision (> 0.15)
- Minimum recall (> 0.15)
- Maximum correlation between rules (< 0.8)

This ensures we keep only the most useful and diverse rules.

In [10]:
R = apply_rules(X_train[num_columns], rules.select("rule").to_series().to_list())
M = compute_metrics(R, y_train)
M = M.filter((pl.col("precision") > 0.15) & (pl.col("recall") > 0.15)).sort(
    "accuracy", descending=True
)
importance = dict(zip(M["rule"], M["f0.5"], strict=False))
uncorrelated_rules = filter_correlated_rules(
    R[M["rule"].to_list()], importance=importance, max_corr=0.8
)

### 5.1 Cumulative Combination

Combines rules cumulatively (rule1 OR rule2 OR ... OR ruleN):

## 5. Combine Rules

Test different rule combination strategies to find the best performing ruleset.

In [9]:
num_rules = R.shape[1]

AttributeError: 'list' object has no attribute 'shape'

In [11]:
num_rules = len(uncorrelated_rules)
R_combined = combine_rules_cumulative(
    R[uncorrelated_rules], output_names=[f"combined_rule_{i}" for i in range(1, num_rules + 1)]
)
M_combined = compute_metrics(R_combined, y_train).sort("accuracy", descending=True)
M_combined.head(3)

shape: (3, 16)
┌─────────────────┬─────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule            ┆ TP  ┆ FP  ┆ TN  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---             ┆ --- ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str             ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞═════════════════╪═════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ combined_rule_1 ┆ 174 ┆ 87  ┆ 447 ┆ … ┆ 0.592845 ┆ 0.568627 ┆ 0.555911 ┆ 1         │
│ combined_rule_2 ┆ 176 ┆ 91  ┆ 443 ┆ … ┆ 0.593592 ┆ 0.571714 ┆ 0.560153 ┆ 1         │
│ combined_rule_3 ┆ 176 ┆ 91  ┆ 443 ┆ … ┆ 0.593592 ┆ 0.571714 ┆ 0.560153 ┆ 1         │
└─────────────────┴─────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

### 5.2 Greedy Search

Uses a greedy algorithm to iteratively select the best rule combination:

In [12]:
R_greedy = combine_rules_greedy(R[uncorrelated_rules], y_train, metric="accuracy")
M_greedy = compute_metrics(R_greedy, y_train)
M_greedy

shape: (1, 16)
┌────────────────────────┬─────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule                   ┆ TP  ┆ FP  ┆ TN  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---                    ┆ --- ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str                    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════════════════╪═════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ ((X["Pclass"] < 3.0) & ┆ 205 ┆ 100 ┆ 417 ┆ … ┆ 0.660225 ┆ 0.655758 ┆ 0.653282 ┆ 4         │
│ (X["Far…               ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
└────────────────────────┴─────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

### 5.3 Beam Search

Uses beam search to explore rule combinations up to a maximum number of rules:

In [13]:
R_beam = combine_rules_beam_search(R[uncorrelated_rules], y_train, metric="accuracy", max_rules=12)
M_beam = compute_metrics(R_beam, y_train)
M_beam.head(3)

shape: (3, 16)
┌────────────────────────┬─────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule                   ┆ TP  ┆ FP  ┆ TN  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---                    ┆ --- ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str                    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════════════════╪═════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ ((X["Pclass"] < 3.0) & ┆ 205 ┆ 100 ┆ 417 ┆ … ┆ 0.660225 ┆ 0.655758 ┆ 0.653282 ┆ 4         │
│ (X["Far…               ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ ((X["Pclass"] < 3.0) & ┆ 205 ┆ 100 ┆ 417 ┆ … ┆ 0.660225 ┆ 0.655758 ┆ 0.653282 ┆ 4         │
│ (X["Far…               ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ ((X["Pclass"] < 3.0) & ┆ 205 ┆ 100 ┆ 417 ┆ … ┆ 0.660225 ┆ 0.655758 ┆ 0.653282 ┆ 4         │
│ (X["Far…               ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
└────────────────────────┴─────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

## 6. Analyze the Best Ruleset

Generate a detailed report for the best performing ruleset from brute force combination:

In [14]:
ruleset = M_beam["rule"][0]
report = generate_rule_performance_report(ruleset, X_train, y_train)
report

shape: (14, 17)
┌────────────┬────────────────────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule_index ┆ rule                   ┆ TP  ┆ FP  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---        ┆ ---                    ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ str                    ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════╪════════════════════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 0          ┆ ((X["Pclass"] < 3.0) & ┆ 205 ┆ 100 ┆ … ┆ 0.660225 ┆ 0.655758 ┆ 0.653282 ┆ 4         │
│            ┆ (X["Far…               ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.0        ┆ (X['Pclass'] < 3.0) &  ┆ 174 ┆ 87  ┆ … ┆ 0.592845 ┆ 0.568627 ┆ 0.555911 ┆ 1         │
│            ┆ (X['Fare…              ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.1        ┆ (X['Fare'] >= 11.1333) ┆ 50  ┆ 11  ┆ … ┆ 0.269542 ┆ 0.214239 ┆ 0.19216  ┆ 1         │
│            ┆ & (X['S…               ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.2        ┆ (X['Fare'] >= 52.5542) ┆ 94  ┆ 32  ┆ … ┆ 0.409586 ┆ 0.349043 ┆ 0.322359 ┆ 1         │
│            ┆ & (X['S…               ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.3        ┆ (X['Fare'] >= 75.25)   ┆ 74  ┆ 23  ┆ … ┆ 0.33713  ┆ 0.277553 ┆ 0.25256  ┆ 1         │
│ …          ┆ …                      ┆ …   ┆ …   ┆ … ┆ …        ┆ …        ┆ …        ┆ …         │
│ 0.1.1      ┆ (X['SibSp'] < 3.0)     ┆ 335 ┆ 510 ┆ … ┆ 0.564448 ┆ 0.674357 ┆ 0.756891 ┆ 1         │
│ 0.1.2      ┆ (X['Age'] < 18.0)      ┆ 61  ┆ 52  ┆ … ┆ 0.30273  ┆ 0.258981 ┆ 0.239592 ┆ 1         │
│ 0.2.0      ┆ (X['Fare'] >= 52.5542) ┆ 104 ┆ 45  ┆ … ┆ 0.423625 ┆ 0.367991 ┆ 0.342782 ┆ 1         │
│ 0.2.1      ┆ (X['SibSp'] < 4.0)     ┆ 339 ┆ 522 ┆ … ┆ 0.563591 ┆ 0.675713 ┆ 0.760431 ┆ 1         │
│ 0.2.2      ┆ (X['Age'] < 63.0)      ┆ 287 ┆ 412 ┆ … ┆ 0.580384 ┆ 0.690159 ┆ 0.77192  ┆ 1         │
└────────────┴────────────────────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

## 7. Generate Predictions on Test Data

Apply the best ruleset to the test data and create a submission file:

In [15]:
X_test = pl.read_csv("../../../kaggle/titanic/test.csv")
y_pred = eval(ruleset.replace("X", "X_test"))

In [16]:
# Create submission file (Kaggle leaderboard score: 0.6411)
pl.DataFrame({"PassengerId": X_test["PassengerId"], "Survived": y_pred}).with_columns(
    pl.col("Survived").cast(pl.Int64)
).write_csv("submission_titanic.csv")