# Titanic Survival Prediction using Iguanas

This notebook demonstrates a complete end-to-end example of using **Iguanas** for rule-based classification on the Kaggle Titanic dataset. 

The workflow includes:
1. Generating the best rule based on the given metric
2. Generating the best ruleset based on the given metric

## 1. Import Libraries

In [1]:
import numpy as np
import polars as pl
from xgboost import XGBClassifier

from iguanas.metrics import compute_metrics
from iguanas.rule_analysis import generate_rule_performance_report
from iguanas.rule_classifier import RuleClassifier
from iguanas.ruleset_classifier import RulesetClassifier

## 2. Load

Load the Titanic training data and separate features from the target variable (Survived).

In [2]:
train = pl.read_csv("../../../../../kaggle/titanic/train.csv").drop("PassengerId")
X_train = train.drop("Survived")
y_train = train["Survived"]

## 3. Generate best rule based on given metric

In [3]:
estimator = XGBClassifier(n_estimators=10, max_depth=4, eval_metric="logloss", random_state=0)
rule_est = RuleClassifier(
    estimator=estimator,
    scale_pos_weight_vec=np.logspace(-3, 3, 10),
)
_ = rule_est.fit(X_train, y_train)
y_pred_train = rule_est.predict(X_train)

In [4]:
M_train = compute_metrics(y_pred_train, y_train)
M_train

shape: (1, 16)
┌───────────────────────┬─────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule                  ┆ TP  ┆ FP  ┆ TN  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---                   ┆ --- ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str                   ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞═══════════════════════╪═════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ (X["Pclass"] < 3.0) & ┆ 176 ┆ 91  ┆ 443 ┆ … ┆ 0.593592 ┆ 0.571714 ┆ 0.560153 ┆ 1         │
│ (X["Fare…             ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
└───────────────────────┴─────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

In [5]:
report = generate_rule_performance_report(rule_est._best_rule_, X_train, y_train)
report

shape: (4, 17)
┌────────────┬────────────────────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule_index ┆ rule                   ┆ TP  ┆ FP  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---        ┆ ---                    ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ str                    ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════╪════════════════════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 0          ┆ (X["Pclass"] < 3.0) &  ┆ 176 ┆ 91  ┆ … ┆ 0.593592 ┆ 0.571714 ┆ 0.560153 ┆ 1         │
│            ┆ (X["Fare…              ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.0        ┆ (X['Pclass'] < 3.0)    ┆ 223 ┆ 177 ┆ … ┆ 0.601078 ┆ 0.619709 ┆ 0.630656 ┆ 1         │
│ 0.1        ┆ (X['Fare'] >= 13.7917) ┆ 234 ┆ 224 ┆ … ┆ 0.585    ┆ 0.619552 ┆ 0.640745 ┆ 1         │
│ 0.2        ┆ (X['Age'] < 64.0)      ┆ 289 ┆ 412 ┆ … ┆ 0.583249 ┆ 0.693942 ┆ 0.776464 ┆ 1         │
└────────────┴────────────────────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

## 4. Generate best ruleset based on given metric

In [6]:
estimator = XGBClassifier(n_estimators=10, max_depth=4, eval_metric="logloss", random_state=0)
ruleset_est = RulesetClassifier(
    estimator=estimator,
    scale_pos_weight_vec=np.logspace(-3, 3, 50),
    opt_metric="accuracy",
    metric_thresholds=[{"name": "accuracy", "operator": ">=", "value": 0.5}],
    max_rules=5,
)
_ = ruleset_est.fit(X_train, y_train)
y_pred_train = ruleset_est.predict(X_train)

In [7]:
M_train = compute_metrics(y_pred_train, y_train)
M_train

shape: (1, 16)
┌────────────────────────┬─────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule                   ┆ TP  ┆ FP  ┆ TN  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---                    ┆ --- ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str                    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════════════════╪═════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ ((X["Pclass"] < 3.0) & ┆ 193 ┆ 92  ┆ 423 ┆ … ┆ 0.648739 ┆ 0.638422 ┆ 0.632787 ┆ 2         │
│ (X["Far…               ┆     ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
└────────────────────────┴─────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

In [8]:
report = generate_rule_performance_report(ruleset_est._best_ruleset_, X_train, y_train)
report

shape: (9, 17)
┌────────────┬────────────────────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬───────────┐
│ rule_index ┆ rule                   ┆ TP  ┆ FP  ┆ … ┆ f1       ┆ f1.5     ┆ f2       ┆ num_rules │
│ ---        ┆ ---                    ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ str                    ┆ i64 ┆ i64 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ u32       │
╞════════════╪════════════════════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 0          ┆ ((X["Pclass"] < 3.0) & ┆ 193 ┆ 92  ┆ … ┆ 0.648739 ┆ 0.638422 ┆ 0.632787 ┆ 2         │
│            ┆ (X["Far…               ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.0        ┆ (X['Pclass'] < 3.0) &  ┆ 174 ┆ 87  ┆ … ┆ 0.592845 ┆ 0.568627 ┆ 0.555911 ┆ 1         │
│            ┆ (X['Fare…              ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.1        ┆ (X['Fare'] >= 10.5) &  ┆ 43  ┆ 6   ┆ … ┆ 0.239554 ┆ 0.187207 ┆ 0.166796 ┆ 1         │
│            ┆ (X['SibS…              ┆     ┆     ┆   ┆          ┆          ┆          ┆           │
│ 0.0.0      ┆ (X['Pclass'] < 3.0)    ┆ 223 ┆ 177 ┆ … ┆ 0.601078 ┆ 0.619709 ┆ 0.630656 ┆ 1         │
│ 0.0.1      ┆ (X['Fare'] >= 13.7917) ┆ 234 ┆ 224 ┆ … ┆ 0.585    ┆ 0.619552 ┆ 0.640745 ┆ 1         │
│ 0.0.2      ┆ (X['Age'] < 61.0)      ┆ 285 ┆ 407 ┆ … ┆ 0.580448 ┆ 0.688918 ┆ 0.769438 ┆ 1         │
│ 0.1.0      ┆ (X['Fare'] >= 10.5)    ┆ 275 ┆ 277 ┆ … ┆ 0.615213 ┆ 0.676315 ┆ 0.716146 ┆ 1         │
│ 0.1.1      ┆ (X['SibSp'] < 3.0)     ┆ 335 ┆ 510 ┆ … ┆ 0.564448 ┆ 0.674357 ┆ 0.756891 ┆ 1         │
│ 0.1.2      ┆ (X['Age'] < 16.0)      ┆ 49  ┆ 34  ┆ … ┆ 0.262735 ┆ 0.216519 ┆ 0.197104 ┆ 1         │
└────────────┴────────────────────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴───────────┘

## 7. Generate Predictions on Test Data

Apply the best ruleset to the test data and create a submission file:

In [9]:
X_test = pl.read_csv("../../../../../kaggle/titanic/test.csv")
y_pred = eval(ruleset_est._best_ruleset_.replace("X", "X_test"))

In [10]:
# Create submission file (Kaggle leaderboard score: 0.612)
pl.DataFrame({"PassengerId": X_test["PassengerId"], "Survived": y_pred}).with_columns(
    pl.col("Survived").cast(pl.Int64)
).write_csv("submission_titanic.csv")